# Generated by Django 5.2.4 on 2025-10-08 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(verbose_name='説明')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='サムネイルURL')),
                ('creator', models.CharField(max_length=100, verbose_name='制作者')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '外部リンク',
                'verbose_name_plural': '外部リンク',
            },
        ),
        migrations.CreateModel(
            name='OnomatopoeiaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10, unique=True, verbose_name='型コード')),
                ('type_name', models.CharField(max_length=100, verbose_name='型名')),
                ('description', models.TextField(verbose_name='説明')),
            ],
            options={
                'verbose_name': 'オノマトペ型',
                'verbose_name_plural': 'オノマトペ型',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='集落名')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '集落',
                'verbose_name_plural': '集落',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(max_length=50, unique=True, verbose_name='話者ID')),
                ('age_range', models.CharField(max_length=20, verbose_name='年代')),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=1, verbose_name='性別')),
                ('language_frequency', models.CharField(choices=[('daily', '日常的に使用'), ('often', 'よく使用'), ('sometimes', 'たまに使用'), ('rarely', 'ほとんど使用しない')], max_length=20, verbose_name='言語使用頻度')),
                ('consent_video', models.BooleanField(default=False, verbose_name='映像公開同意')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.village', verbose_name='集落')),
            ],
            options={
                'verbose_name': '話者',
                'verbose_name_plural': '話者',
            },
        ),
        migrations.CreateModel(
            name='LanguageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('onomatopoeia_text', models.CharField(max_length=100, verbose_name='オノマトペ')),
                ('meaning', models.TextField(verbose_name='意味')),
                ('usage_example', models.TextField(verbose_name='用例')),
                ('phonetic_notation', models.TextField(blank=True, verbose_name='音声記号')),
                ('file_type', models.CharField(choices=[('audio', '音声'), ('video', '映像'), ('image', '画像')], max_length=10, verbose_name='ファイル種類')),
                ('file_path', models.URLField(max_length=1024, verbose_name='ファイルURL')),
                ('thumbnail_path', models.URLField(blank=True, max_length=1024, verbose_name='サムネイルURL')),
                ('recorded_date', models.DateField(verbose_name='収録日')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('onomatopoeia_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.onomatopoeiatype', verbose_name='型')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.speaker', verbose_name='話者')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.village', verbose_name='集落')),
            ],
            options={
                'verbose_name': '言語記録',
                'verbose_name_plural': '言語記録',
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='GeographicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content_type', models.CharField(choices=[('drone', 'ドローン映像'), ('photo', '写真'), ('panorama', 'パノラマ')], max_length=20, verbose_name='コンテンツ種類')),
                ('file_path', models.URLField(max_length=1024, verbose_name='ファイルURL')),
                ('thumbnail_path', models.URLField(blank=True, max_length=1024, verbose_name='サムネイルURL')),
                ('description', models.TextField(verbose_name='説明')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('captured_date', models.DateField(verbose_name='撮影日')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.village', verbose_name='集落')),
            ],
            options={
                'verbose_name': '地理環境データ',
                'verbose_name_plural': '地理環境データ',
                'ordering': ['-captured_date'],
            },
        ),
    ]
