# Generated by Django 5.2.4 on 2025-10-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='languagerecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
