# Generated by Django 5.2.4 on 2025-10-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0002_languagerecord_latitude_languagerecord_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='language_frequency',
        ),
        migrations.AddField(
            model_name='languagerecord',
            name='language_frequency',
            field=models.CharField(choices=[('daily', '日常的に使用'), ('often', 'よく使用'), ('sometimes', 'たまに使用'), ('rarely', 'ほとんど使用しない')], default='often', max_length=20, verbose_name='言語使用頻度'),
            preserve_default=False,
        ),
    ]
