# Generated by Django 5.2.4 on 2025-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0003_remove_speaker_language_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicrecord',
            name='content_type',
            field=models.CharField(choices=[('drone_video', 'ドローン映像'), ('drone_photo', 'ドローン画像'), ('other', 'その他')], max_length=20, verbose_name='コンテンツ種類'),
        ),
    ]
