# Generated by Django 5.2.4 on 2025-10-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0004_alter_geographicrecord_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagerecord',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.village', verbose_name='集落'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='age_range',
            field=models.CharField(choices=[('10-20', '10-20代'), ('20-30', '20-30代'), ('30-40', '30-40代'), ('40-50', '40-50代'), ('50-60', '50-60代'), ('60-70', '60-70代'), ('70-80', '70-80代')], max_length=10, verbose_name='年代'),
        ),
    ]
