# Generated by Django 5.2.4 on 2025-10-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0005_alter_languagerecord_village_alter_speaker_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='age_range',
            field=models.CharField(choices=[('30-40', '30-40代'), ('40-50', '40-50代'), ('50-60', '50-60代'), ('60-70', '60-70代'), ('70-80', '70-80代'), ('80-90', '80-90代'), ('90-100', '90-100代')], max_length=10, verbose_name='年代'),
        ),
    ]
