# Generated by Django 5.2.4 on 2025-10-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0006_alter_speaker_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='age_range',
            field=models.CharField(choices=[('30-39', '30d'), ('40-49', '40代'), ('50-59', '50代'), ('60-69', '60代'), ('70-79', '70代'), ('80-89', '80代'), ('90-99', '90代'), ('100+', '100歳以上')], max_length=10, verbose_name='年代'),
        ),
    ]
