# Generated by Django 5.2.4 on 2025-10-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0007_alter_speaker_age_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagerecord',
            name='title',
        ),
    ]
