# Generated by Django 5.2.4 on 2025-10-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0008_remove_languagerecord_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalLink',
        ),
        #migrations.RemoveField(
        #   model_name='languagerecord',
        #    name='latitude',
        #),
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='longitude',
        #),
        #migrations.RemoveField(
        #   model_name='languagerecord',
        #    name='village',
        #),
        migrations.AlterField(
            model_name='languagerecord',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='language_archive.speaker', verbose_name='話者'),
        ),
    ]
