# Generated by Django 5.2.4 on 2025-10-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0009_delete_externallink_remove_languagerecord_latitude_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #   model_name='languagerecord',
        #   name='latitude',
        #),
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='longitude',
        #),
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='village',
        #),
        migrations.AlterField(
            model_name='speaker',
            name='age_range',
            field=models.CharField(choices=[('30-39', '30代'), ('40-49', '40代'), ('50-59', '50代'), ('60-69', '60代'), ('70-79', '70代'), ('80-89', '80代'), ('90-99', '90代'), ('100+', '100歳以上')], max_length=10, verbose_name='年代'),
        ),
    ]
