# Generated by Django 5.2.4 on 2025-10-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0010_remove_languagerecord_latitude_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #   model_name='languagerecord',
        #    name='latitude',
        #),
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='longitude',
        #),
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='village',
        #),
    ]
