# Generated by Django 5.2.4 on 2025-10-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0011_remove_languagerecord_latitude_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='latitude',
        #),
        #migrations.RemoveField(
        #    model_name='languagerecord',
        #    name='longitude',
        #),
        migrations.AlterField(
            model_name='languagerecord',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_archive.village', verbose_name='関連集落'),
        ),
    ]
