# Generated by Django 5.2.4 on 2025-10-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0012_remove_languagerecord_latitude_and_more'),
    ]

    operations = [
        # latitude and longitude fields were already removed in previous migrations
        # No operations needed for this migration
    ]
