# Generated by Django 5.2.4 on 2025-10-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0013_add_village_field_back'),
    ]

    operations = [
        # latitude and longitude fields were already removed in previous migrations
        # No operations needed for this migration
    ]
