# Generated by Django 5.2.4 on 2025-10-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_archive', '0014_add_village_field_to_languagerecord'),
    ]

    operations = [
        # latitude and longitude fields were already removed in previous migrations
        # village field was never actually added to the database, so no removal needed
    ]
